learningcenter_:
    path: /learningcenter/
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\LearningCenterController::dashboard'
        _token_check: true
        _scope: frontend
        _menu_key: home

####################
#Project Management#
####################
learningcenter_projects.confirm:
    path: /learningcenter/projects/{alias}/confirm
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\ProjectController::confirmAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects

#################
#User Management#
#################
learningcenter_user:
    path: /learningcenter/users
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\ListsController::studentAction'
        _token_check: true
        _scope: frontend
        _menu_key: users


learningcenter_user.details:
    path: /learningcenter/users/{username}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\ListsController::detailsAction'
        _token_check: true
        _scope: frontend

learningcenter_members.ajax.search:
    path: /learningcenter/projects/members/search/ajax
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\MemberController::ajaxSearchAction'
        _token_check: true
        _scope: frontend

learningcenter_members.ajax.add:
    path: /learningcenter/projects/members/add/ajax
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\MemberController::ajaxAddAction'
        _token_check: true
        _scope: frontend

learningcenter_files.details:
    path: /learningcenter/filemanager/details/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::detailAction'
        _token_check: true
        _scope: frontend

learningcenter_files.upload:
    path: /learningcenter/filemanager/upload/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::uploadAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.download:
    path: /learningcenter/filemanager/download/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::downloadAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.delete:
    path: /learningcenter/filemanager/delete/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::deleteAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.folder:
    path: /learningcenter/filemanager/folder/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::folderAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.share.edit:
    path: /learningcenter/filemanager/share/edit/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::editShareAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.share:
    path: /learningcenter/filemanager/share/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::shareAction'
        _token_check: true
        _scope: frontend
        fid: null



learningcenter_files:
    path: /learningcenter/filemanager/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::mainAction'
        _token_check: true
        _scope: frontend
        fid: null
        _menu_key: files

learningcenter_files.ajax.load:
    path: /learningcenter/filemanager/load/{fid}
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\FilesController::loadFiles'
        _token_check: true
        _scope: frontend
        fid: null
    options:
      expose: true

learningcenter_catalog:
    path: /learningcenter/catalog
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\CatalogController::mainAction'
        _token_check: true
        _scope: frontend
        _menu_key: catalog

learningcenter_login:
    path: /learningcenter/login
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\LoginController::loginAction'
        _token_check: true
        _scope: frontend

learningcenter_logout:
    path: /learningcenter/logout
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\LoginController::logoutAction'
        _token_check: true
        _scope: frontend

###############
#Notifications#
###############
learningcenter_notifications.ajax.load:
    path: /learningcenter/notifications/ajax/load
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\NotificationsController::ajaxLoadAction'
        _token_check: true
        _scope: frontend



learningcenter_security.login:
    path: /learningcenter/security/login
    defaults:
        _controller: 'App\XRayLP\LearningCenterBundle\Controller\SecurityController::loginAction'
        _token_check: true
        _scope: frontend


#######
#Extra#
#######
frontend_demo_remove_trailing_slash:
    path: /learningcenter/{url}
    defaults:
        _controller: LearningCenterBundle:LearningCenter:removeTrailingSlash
        _scope: frontend
        _token_check: false
    requirements:
        url: .*/$
    methods: [GET]