<?php
/**
 * @link https://github.com/XRayLP/learning-center-bundle
 * @copyright Copyright (c) 2018 Niklas Loos <https://github.com/XRayLP>
 * @license GPL-3.0 <https://github.com/XRayLP/learning-center-bundle/blob/master/LICENSE>
 */

namespace XRayLP\LearningCenterBundle\DataQueries;


class DataSites
{

    public static function getDataSites()
    {
        $chmod = 'a:9:{i:0;s:2:"u1";i:1;s:2:"u2";i:2;s:2:"u3";i:3;s:2:"u4";i:4;s:2:"u5";i:5;s:2:"u6";i:6;s:2:"g4";i:7;s:2:"g5";i:8;s:2:"g6";}';

        return $pages = array(
            '1' => array(
                'id'        => 1,
                'pid'       => 0,
                'sorting'   => 128,
                'tstamp'    => time(),
                'title'     => 'Learning Center',
                'alias'     => 'learning-center',
                'type'      => 'root',
                'language'  => 'de',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'fallback'  => 1,
                'layout'    => 1,
                'chmod'   => $chmod,
                'published' => 1,
            ),
            '2' => array(
                'id'        => 2,
                'pid'       => 1,
                'sorting'   => 64,
                'tstamp'    => time(),
                'title'     => 'Extern',
                'alias'     => 'extern',
                'type'      => 'forward',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 4,
                'chmod'   => $chmod,
                'includeLayout' => 1,
                'layout'    => 1,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '3' => array(
                'id'        => 3,
                'pid'       => 1,
                'sorting'   => 192,
                'tstamp'    => time(),
                'title'     => 'Intern',
                'alias'     => 'intern',
                'type'      => 'forward',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'   => $chmod,
                'protected '=> '1',
                'groups'    => 'a:2:{i:0;s:1:"4";i:1;s:1:"1";}',
                'includeLayout' => 1,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '4' => array(
                'id'        => 4,
                'pid'       => 2,
                'sorting'   => 128,
                'tstamp'    => time(),
                'title'     => 'Login',
                'alias'     => 'login',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'hide'      => 1,
                'chmod'     => $chmod,
                'layout'    => 1,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '5' => array(
                'id'        => 5,
                'pid'       => 3,
                'sorting'   => 128,
                'tstamp'    => time(),
                'title'     => 'Startseite',
                'alias'     => 'startseite',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '6' => array(
                'id'        => 6,
                'pid'       => 3,
                'sorting'   => 192,
                'tstamp'    => time(),
                'title'     => 'Lernkatalog',
                'alias'     => 'lernkatalog',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '7' => array(
                'id'        => 7,
                'pid'       => 3,
                'sorting'   => 240,
                'tstamp'    => time(),
                'title'     => 'Speicher',
                'alias'     => 'speicher',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '8' => array(
                'id'        => 8,
                'pid'       => 3,
                'sorting'   => 244,
                'tstamp'    => time(),
                'title'     => 'Projekte',
                'alias'     => 'projekte',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '9' => array(
                'id'        => 9,
                'pid'       => 3,
                'sorting'   => 248,
                'tstamp'    => time(),
                'title'     => 'Listen',
                'alias'     => 'listen',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '10' => array(
                'id'        => 10,
                'pid'       => 3,
                'sorting'   => 256,
                'tstamp'    => time(),
                'title'     => 'Profil',
                'alias'     => 'profil',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '11' => array(
                'id'        => 11,
                'pid'       => 3,
                'sorting'   => 384,
                'tstamp'    => time(),
                'title'     => 'Abmeldung',
                'alias'     => 'abmeldung',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'hide'      => 1,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '12' => array(
                'id'        => 12,
                'pid'       => 8,
                'sorting'   => 128,
                'tstamp'    => time(),
                'title'     => 'Details',
                'alias'     => 'details',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'     => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '13' => array(
                'id'        => 13,
                'pid'       => 9,
                'sorting'   => 128,
                'tstamp'    => time(),
                'title'     => 'Schülerliste',
                'alias'     => 'schülerliste',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'   => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
            '14' => array(
                'id'        => 14,
                'pid'       => 9,
                'sorting'   => 64,
                'tstamp'    => time(),
                'title'     => 'Klassenliste',
                'alias'     => 'klassenliste',
                'type'      => 'regular',
                'robots'    => 'index,follow',
                'redirect'  => 'permanent',
                'jumpTo'    => 0,
                'chmod'   => $chmod,
                'layout'    => 2,
                'sitemap'   => 'map_default',
                'published' => 1,
            ),
        );
    }
}