learningcenter:
    path: /learningcenter
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\LearningCenterController::mainAction'
        _token_check: true
        _scope: frontend
        _menu_key: home

####################
#Project Management#
####################
learningcenter_projects:
    path: /learningcenter/projects
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::mainAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects

learningcenter_projects.create:
    path: /learningcenter/projects/create
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::createAction'
        _token_check: true
        _scope: frontend
    requirements:
        - "@event_dispatcher"

learningcenter_projects.details:
    path: /learningcenter/projects/{alias}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::detailAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects_home|projects

learningcenter_projects.details.members:
    path: /learningcenter/projects/members/{alias}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::membersAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects_members|projects

learningcenter_projects.details.events:
    path: /learningcenter/projects/events/{alias}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::detailAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects_events

learningcenter_projects.details.chat:
    path: /learningcenter/projects/chat/{alias}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::detailAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects_chat

learningcenter_projects.edit:
    path: /learningcenter/projects/edit/{alias}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::updateAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects

learningcenter_projects.confirm:
    path: /learningcenter/projects/{alias}/confirm
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::confirmAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects

learningcenter_projects.confirm.process:
    path: /learningcenter/projects/{alias}/confirm/{confirm}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ProjectController::confirmProcessAction'
        _token_check: true
        _scope: frontend
        _menu_key: projects

#################
#User Management#
#################
learningcenter_user:
    path: /learningcenter/users
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ListsController::studentAction'
        _token_check: true
        _scope: frontend
        _menu_key: users


learningcenter_user.details:
    path: /learningcenter/users/{username}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\ListsController::detailsAction'
        _token_check: true
        _scope: frontend

learningcenter_members.ajax.search:
    path: /learningcenter/projects/members/search/ajax
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\MemberController::ajaxSearchAction'
        _token_check: true
        _scope: frontend

learningcenter_members.ajax.add:
    path: /learningcenter/projects/members/add/ajax
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\MemberController::ajaxAddAction'
        _token_check: true
        _scope: frontend

learningcenter_files.details:
    path: /learningcenter/filemanager/details/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::detailAction'
        _token_check: true
        _scope: frontend

learningcenter_files.upload:
    path: /learningcenter/filemanager/upload/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::uploadAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.download:
    path: /learningcenter/filemanager/download/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::downloadAction'
        _token_check: true
        _scope: frontend

learningcenter_files.delete:
    path: /learningcenter/filemanager/delete/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::deleteAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.folder:
    path: /learningcenter/filemanager/folder/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::folderAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files.share:
    path: /learningcenter/filemanager/share/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::shareAction'
        _token_check: true
        _scope: frontend
        fid: null

learningcenter_files:
    path: /learningcenter/filemanager/{fid}
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\FilesController::mainAction'
        _token_check: true
        _scope: frontend
        fid: null
        _menu_key: files

learningcenter_catalog:
    path: /learningcenter/catalog
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\CatalogController::mainAction'
        _token_check: true
        _scope: frontend
        _menu_key: catalog

learningcenter_login:
    path: /learningcenter/login
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\LoginController::loginAction'
        _token_check: true
        _scope: frontend

learningcenter_logout:
    path: /learningcenter/logout
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\LoginController::logoutAction'
        _token_check: true
        _scope: frontend

###############
#Notifications#
###############
learningcenter_notifications.ajax.load:
    path: /learningcenter/notifications/ajax/load
    defaults:
        _controller: 'XRayLP\LearningCenterBundle\Controller\NotificationsController::ajaxLoadAction'
        _token_check: true
        _scope: frontend

