# config/services.yml
services:
    kernel_bundle:
        class: XRayLP\LearningCenterBundle
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]
    learningcenter.project:
        class: XRayLP\LearningCenterBundle\Service\ProjectService
        arguments:
        - '@router'
        - '@doctrine.orm.default_entity_manager'

    learningcenter.users:
        class: XRayLP\LearningCenterBundle\Service\MemberService

    learningcenter.files:
        class: XRayLP\LearningCenterBundle\Service\FilesService
        arguments:
        - '@router'
        - '@doctrine.orm.default_entity_manager'

    learningcenter.filemanager:
        class: XRayLP\LearningCenterBundle\Service\Filemanager
        arguments:
        - '@router'
        - '@doctrine.orm.default_entity_manager'
        - '@form.factory'

    learningcenter.catalog:
        class: XRayLP\LearningCenterBundle\Service\Catalog
        arguments:
        - '@router'