# config/services.yml
services:
    kernel_bundle:
        class: XRayLP\LearningCenterBundle
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    learningcenter.filemanager:
        class: XRayLP\LearningCenterBundle\Service\Filemanager
        arguments:
        - '@router'
        - '@doctrine.orm.default_entity_manager'
        - '@form.factory'

    learningcenter.catalog:
        class: XRayLP\LearningCenterBundle\Service\Catalog
        arguments:
        - '@router'

    learningcenter.security.authentication_provider:
        class: Contao\CoreBundle\Security\Authentication\Provider\AuthenticationProvider
        abstract: true
        arguments:
            - ~ # User provider
            - ~ # User checker
            - ~ # Provider-shared key
            - "@security.encoder_factory"
            - "@contao.framework"
            - "@translator"
            - "@request_stack"
            - "@mailer"

    acme.post_generate_schema_table:
        class: XRayLP\LearningCenterBundle\EventListener\PostGenerateSchemaTable
        tags:
            - {name: doctrine.event_listener, event: postGenerateSchemaTable }

    ##############
    #Menu Builder#
    ##############
    lerningcenter.menu_builder:
        class: XRayLP\LearningCenterBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", '@learningcenter.security.voter.route_key', '@request_stack']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createProjectDetailsMenu, alias: project }

    ###########
    #Security #
    ###########
    learningcenter.security.voter.project:
        class: XRayLP\LearningCenterBundle\Security\Authorization\Voter\ProjectVoter
        tags:
            - { name: security.voter }

    learningcenter.security.voter.project_member:
        class: XRayLP\LearningCenterBundle\Security\Authorization\Voter\ProjectMemberVoter
        tags:
            - { name: security.voter }

    learningcenter.security.voter.route_key:
        class: XRayLP\LearningCenterBundle\Security\Authorization\Voter\RouteKeyVoter
        scope: request
        tags:
            - { name: knp_menu.voter }

    ##########
    #Listener#
    ##########

    # authentication failure event listener
    acme.security.authentication_failure_event_listener:
        class: XRayLP\LearningCenterBundle\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

    # authentication success event listener
    acme.security.interactive_login_listener:
        class: XRayLP\LearningCenterBundle\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    learningcenter.security.frontend_user_provider:
        class: XRayLP\LearningCenterBundle\Member\ContaoUserProvider
        arguments:
            - "@contao.framework"
            - "@session"
            - "XRayLP\\LearningCenterBundle\\Member\\FrontendUser"
            - "@logger"

    learningcenter.listener.project_event_listener:
        class: XRayLP\LearningCenterBundle\EventListener\ProjectEventListener
        arguments:
          - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: kernel.event_listener, event: project.create.success, method: onProjectCreateSuccess }

    learningcenter.listener.authentication_event_listener:
        class: XRayLP\LearningCenterBundle\EventListener\AuthenticationEventListener
        arguments:
          - '@twig'
          - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    learningcenter.listener.member_entity_listener:
        class: XRayLP\LearningCenterBundle\EventListener\MemberEntityListener
        tags:
            - { name: doctrine.event_listener, event: postLoad, priority: 1000 }
            - { name: doctrine.event_listener, event: preUpdate }
        arguments:
            - '@doctrine'

    learningcenter.listener.member_group_entity_listener:
        class: XRayLP\LearningCenterBundle\EventListener\MemberGroupEntityListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments:
            - '@doctrine'

    #############
    #Controller#
    ############
    XRayLP\LearningCenterBundle\Controller\ProjectController:
        public: true
        arguments:
            - '@event_dispatcher'
            - '@translator.default'

    XRayLP\LearningCenterBundle\Controller\NotificationsController:
        public: true
        arguments:
            - '@doctrine'

    XRayLP\LearningCenterBundle\Controller\SecurityController:
        public: true
        arguments:
            - '@security.authentication_utils'
    ############
    #Extensions#
    ############
    learningcenter.notifications_extension:
        class: XRayLP\LearningCenterBundle\Extension\NotificationsExtension
        arguments:
            - "@security.token_storage"
            - "@doctrine"
            - "@translator.default"
        tags:
            - { name: twig.extension }

    learningcenter.member_extension:
        class: XRayLP\LearningCenterBundle\Extension\MemberExtension
        arguments:
            - "@security.token_storage"
            - "@doctrine"
        tags:
            - { name: twig.extension }

    #######
    #Utils#
    #######
    learningcenter.utils.blob_converter:
        class: XRayLP\LearningCenterBundle\Util\BlobConverter
        arguments:
            - "@doctrine"

    ###########
    #Entities#
    ##########
    learningcenter.entity.member:
        class: XRayLP\LearningCenterBundle\Entity\Member
        arguments:
            - "@doctrine"