framework:
    workflows:
        project_creating:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'state'
            supports:
                - 'XRayLP\LearningCenterBundle\Entity\Project'
            initial_place: name
            places:
                - name
                - member
                - leader
                - done
            transitions:
                members:
                    from: name
                    to:   member
                need_leader:
                    from: member
                    to: leader
                done:
                    from: member
                    to: done
                confirm:
                    from: leader
                    to:   done
